name: popcorn_api
author: acnologla2121@gmail.com
version: 1.1.2
homepage: https://github.com/Acnologla/PopcornAPi/
environment:
 sdk: ">=2.0.0-dev.63.0 <3.0.0"
description: interact with popcorn-api easily
dependencies:
  http: ^0.12.0